In [1]:
import numpy

import fhtbioinfpy.genomic_serial_corr.genomic_serial_corr as gensc

# import plotly.express as pltxpr

In [5]:
input_cov = "/home/ec2-user/balt_wkdir/temp/H3K27ac_OCILY10_DMSO_chr1_fragments_std_norm.npy"
input_ref_result = "/home/ec2-user/balt_wkdir/118_serial_correlation/code/NS-24.0018/results/coverage/rfft_fragment_coverage_std_norm/H3K27ac_OCILY10_DMSO_chr1_fragments_fragment_cov_std_norm_rfft.npy"

In [4]:
cov_arr = numpy.load(input_cov)
print(cov_arr.dtype)
print(cov_arr.shape)
cov_arr

float32
(248956422,)


array([-0.2278336, -0.2278336, -0.2278336, ..., -0.2278336, -0.2278336,
       -0.2278336], dtype=float32)

In [6]:
ref_result_arr = numpy.load(input_ref_result)
print(ref_result_arr.dtype)
print(ref_result_arr.shape)
ref_result_arr

complex128
(134217729,)


array([-8.72451392e+01+0.00000000e+00j,  6.62471600e+06+4.15212205e+06j,
       -5.75782721e+06-2.02409250e+06j, ...,
       -4.49267453e+02-2.71558116e+02j,  1.14575821e+02-2.99928410e+01j,
        2.67312880e+02+0.00000000e+00j])

In [7]:
rfft_cov_arr = gensc.calculate_rfft(cov_arr)
print(rfft_cov_arr.dtype)
print(rfft_cov_arr.shape)
rfft_cov_arr

complex128
(134217729,)


array([-8.72451392e+01+0.00000000e+00j,  6.62471600e+06+4.15212205e+06j,
       -5.75782721e+06-2.02409250e+06j, ...,
       -4.49267453e+02-2.71558116e+02j,  1.14575821e+02-2.99928410e+01j,
        2.67312880e+02+0.00000000e+00j])

In [8]:
assert ref_result_arr.shape == rfft_cov_arr.shape

In [9]:
diff_arr = rfft_cov_arr - ref_result_arr
diff_arr

array([0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j])

In [10]:
power_spec_diff_arr = diff_arr * numpy.conj(diff_arr)
power_spec_diff_arr

array([0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j])

In [13]:
sum_power_spec_real = numpy.sum(numpy.abs(numpy.real(power_spec_diff_arr)))
print(sum_power_spec_real)
assert sum_power_spec_real < 1e-10

0.0


In [14]:
sum_power_spec_imag = numpy.sum(numpy.abs(numpy.imag(power_spec_diff_arr)))
print(sum_power_spec_imag)
assert sum_power_spec_imag < 1e-10

0.0
